% generates all SeventhsBass chord types
function chordmode =  chordTypesGen

% chordmode parameters
chordmodeparam = struct(...
    'triadcontrol', 0,...
    'tetradcontrol', 0.25,...
    'pentacontrol', 0,...
    'hexacontrol',0,...
    ...
    'enUni', 0,...
    'enDyad', 0,...
    'enMajMin', 1,...
    'enSus', 0,...
    'enAdd', 0,...
    'enSixthMaj', 0,...
    'enSixthMin', 0,...
    'enSeventh', 1,...
    'enExtended', 0,...
    'enAugDim', 0,...
    'enAugDim7', 0,...
    'enMajBass', 1,...
    'enMinBass', 1,...
    'enMajSeventhBass', 1,...
    'enMinSeventhBass', 1,...
    'en7SeventhBass', 1,...
    'enOtherSlash', 0);

chordmode = buildChordMode(chordmodeparam);